### ISSUE TITLE
Make names more descriptive

### ISSUE THREAD

**Issue by dmiklic** [BigGuido55/ROS_robot_speed_regulation#6]
Package and node names should better describe their functionality. My suggestions:

ROS_robot_speed_regulation -> tracking_navigation (both package and repo name)
tf_publish_actor -> fake_tracking
tf_distance_listener -> relative_pose_publisher (instead of printing to stdout, the node should publish geometry_msgs/PoseStamped)
actor -> object_name
map -> global_frame
robot -> tracking_frame
initialLaunch -> fake_tracking

**Comment by TKomericki** [comment]
Closed by 09b5df2
